### ISSUE TITLE
[Feature Request] Cart Weight Configuration

### ISSUE THREAD

**Issue by Xiaminou** [AzumattDev/CraftyCartsRemake#5]
It would be nice to be able to configure the empty weight for all the carts.
Pulling a crafting station should be harder than pulling an empty cart, and as it stands they're too light and tend to tip over very easily, the increase in weight would most likely help with stability.

**Comment by AzumattDev** [comment]
https://valheim.thunderstore.io/package/Azumatt/HaulersHelper/
